### ISSUE TITLE
Could you please add a readme file explaining how to use this?

### ISSUE THREAD

**Issue by Whitespace404** [devmorra/ZoomAttendanceParser#1]
Please add a readme file with some basic explanation

**Comment by devmorra** [comment]
All done. Let me know if you have further questions. I'm also curious as to how you found this and if you had a particular use for it?

**Comment by Whitespace404** [comment]
Thanks so much! I wanted to create a quick python script that got the current participants of a zoom meeting but I decided to first check if it had been done before. A quick GitHub search got me to this repo. Thanks for the quick response!

**Comment by devmorra** [comment]
This doesn't grab the current participants, unfortunately, but does
post-meeting analysis. I believe it requires that the meeting be ended for
15 minutes before it can grab the report.

**Comment by Whitespace404** [comment]
That would be fine for my use case.

**Comment by devmorra** [comment]
Cool! Let me know how it works for you! It's pretty cobbled together.
